CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  codigo_registro VARCHAR(255) UNIQUE,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE usuarios
ADD COLUMN IF NOT EXISTS permissoes INT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS filas (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  senha_atual INT NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
