CREATE TABLE IF NOT EXISTS persons (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NULL UNIQUE,
  cpf VARCHAR(255) NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  code VARCHAR(255) UNIQUE,
  permissions INT NOT NULL DEFAULT 0,
  person_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE users
ADD CONSTRAINT fk_user_person FOREIGN KEY (person_id) REFERENCES persons(id);
CREATE TABLE IF NOT EXISTS queues (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  actual_number INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  number INT NOT NULL,
  person_id INT NULL,
  responsive_id INT NOT NULL,
  queue_id INT NOT NULL,
  finish_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE reports
ADD CONSTRAINT fk_report_queue FOREIGN KEY (queue_id) REFERENCES queues(id);
ALTER TABLE reports
ADD CONSTRAINT fk_report_person FOREIGN KEY (person_id) REFERENCES persons(id);
ALTER TABLE reports
ADD CONSTRAINT fk_report_user FOREIGN KEY (responsive_id) REFERENCES users(id);
