// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     pgtype.Text      `json:"phone"`
	Cpf       pgtype.Text      `json:"cpf"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Queue struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	ActualNumber int32            `json:"actual_number"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Report struct {
	ID           int32            `json:"id"`
	Number       int32            `json:"number"`
	PersonID     pgtype.Int4      `json:"person_id"`
	ResponsiveID int32            `json:"responsive_id"`
	QueueID      int32            `json:"queue_id"`
	FinishAt     pgtype.Timestamp `json:"finish_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID          int32            `json:"id"`
	Email       string           `json:"email"`
	Password    string           `json:"password"`
	Code        pgtype.Text      `json:"code"`
	Permissions int32            `json:"permissions"`
	PersonID    int32            `json:"person_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
