// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: report.sql

package database

import (
	"context"
)

const getReports = `-- name: GetReports :many
SELECT id, email, password, code, permissions, person_id, created_at, updated_at FROM users
LIMIT $1 OFFSET $2
`

type GetReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetReports(ctx context.Context, arg GetReportsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Code,
			&i.Permissions,
			&i.PersonID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
